[2024-08-23 09:59:01,097] {processor.py:153} INFO - Started process (PID=21780) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 09:59:01,097] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 09:59:01,097] {logging_mixin.py:115} INFO - [2024-08-23 09:59:01,097] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 09:59:01,099] {logging_mixin.py:115} INFO - [2024-08-23 09:59:01,098] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 09:59:01,099] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 09:59:01,109] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.014 seconds
[2024-08-23 09:59:33,139] {processor.py:153} INFO - Started process (PID=21991) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 09:59:33,140] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 09:59:33,140] {logging_mixin.py:115} INFO - [2024-08-23 09:59:33,140] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 09:59:33,141] {logging_mixin.py:115} INFO - [2024-08-23 09:59:33,141] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 09:59:33,141] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 09:59:33,152] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.014 seconds
[2024-08-23 10:00:05,052] {processor.py:153} INFO - Started process (PID=22197) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:00:05,053] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:00:05,053] {logging_mixin.py:115} INFO - [2024-08-23 10:00:05,053] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:00:05,054] {logging_mixin.py:115} INFO - [2024-08-23 10:00:05,054] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:00:05,054] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:00:05,065] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.014 seconds
[2024-08-23 10:00:39,152] {processor.py:153} INFO - Started process (PID=22414) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:00:39,152] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:00:39,153] {logging_mixin.py:115} INFO - [2024-08-23 10:00:39,153] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:00:39,154] {logging_mixin.py:115} INFO - [2024-08-23 10:00:39,153] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:00:39,154] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:00:39,165] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.015 seconds
[2024-08-23 10:01:11,422] {processor.py:153} INFO - Started process (PID=22623) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:01:11,423] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:01:11,423] {logging_mixin.py:115} INFO - [2024-08-23 10:01:11,423] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:01:11,424] {logging_mixin.py:115} INFO - [2024-08-23 10:01:11,424] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:01:11,425] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:01:11,435] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.014 seconds
[2024-08-23 10:01:45,169] {processor.py:153} INFO - Started process (PID=22841) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:01:45,170] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:01:45,170] {logging_mixin.py:115} INFO - [2024-08-23 10:01:45,170] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:01:45,171] {logging_mixin.py:115} INFO - [2024-08-23 10:01:45,171] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:01:45,172] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:01:45,183] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.016 seconds
[2024-08-23 10:02:16,542] {processor.py:153} INFO - Started process (PID=23043) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:02:16,543] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:02:16,543] {logging_mixin.py:115} INFO - [2024-08-23 10:02:16,543] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:02:16,544] {logging_mixin.py:115} INFO - [2024-08-23 10:02:16,544] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:02:16,544] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:02:16,555] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.015 seconds
[2024-08-23 10:02:47,328] {processor.py:153} INFO - Started process (PID=23243) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:02:47,328] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:02:47,329] {logging_mixin.py:115} INFO - [2024-08-23 10:02:47,329] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:02:47,330] {logging_mixin.py:115} INFO - [2024-08-23 10:02:47,329] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:02:47,330] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:02:47,342] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.015 seconds
[2024-08-23 10:03:18,107] {processor.py:153} INFO - Started process (PID=23443) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:03:18,107] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:03:18,108] {logging_mixin.py:115} INFO - [2024-08-23 10:03:18,108] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:03:18,109] {logging_mixin.py:115} INFO - [2024-08-23 10:03:18,109] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:03:18,109] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:03:18,124] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.019 seconds
[2024-08-23 10:03:48,847] {processor.py:153} INFO - Started process (PID=23642) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:03:48,848] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:03:48,849] {logging_mixin.py:115} INFO - [2024-08-23 10:03:48,849] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:03:48,850] {logging_mixin.py:115} INFO - [2024-08-23 10:03:48,849] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:03:48,850] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:03:48,861] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.015 seconds
[2024-08-23 10:04:19,628] {processor.py:153} INFO - Started process (PID=23840) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:04:19,629] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:04:19,629] {logging_mixin.py:115} INFO - [2024-08-23 10:04:19,629] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:04:19,630] {logging_mixin.py:115} INFO - [2024-08-23 10:04:19,630] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:04:19,631] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:04:19,642] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.015 seconds
[2024-08-23 10:04:51,006] {processor.py:153} INFO - Started process (PID=24041) to work on /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:04:51,006] {processor.py:641} INFO - Processing file /root/Documentos/pipeline-airflow/dags/my_first_dag.py for tasks to queue
[2024-08-23 10:04:51,007] {logging_mixin.py:115} INFO - [2024-08-23 10:04:51,007] {dagbag.py:507} INFO - Filling up the DagBag from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:04:51,008] {logging_mixin.py:115} INFO - [2024-08-23 10:04:51,007] {dagbag.py:320} ERROR - Failed to import: /root/Documentos/pipeline-airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/root/Documentos/pipeline-airflow/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Documentos/pipeline-airflow/dags/my_first_dag.py", line 10
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-08-23 10:04:51,008] {processor.py:653} WARNING - No viable dags retrieved from /root/Documentos/pipeline-airflow/dags/my_first_dag.py
[2024-08-23 10:04:51,018] {processor.py:161} INFO - Processing /root/Documentos/pipeline-airflow/dags/my_first_dag.py took 0.014 seconds
